name: On demand CI/CD Pipeline

# Utilisation sur githubaction à la demande
on:
  workflow_dispatch:
    inputs:
      encironement:
        description: ''
        required: true
        default: 'dev'
        options:
          - main
          - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1' # Node.js version compatible avec Angular

      - name: Install and Build Angular
        run: |
          cd src/main/angular
          npm install
          npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Run Backend Tests
        run: mvn clean test  # Exécution des tests Java

      - name: Generate JaCoCo Test Coverage Report
        run: mvn verify  # Génération du rapport de couverture des tests
